### ISSUE TITLE
installkernel: Install system-provided {pre,post}inst scripts in /usr

### ISSUE THREAD

**Issue by mid-kid** [projg2/installkernel-gentoo#18]
I have a bit of an odd setup where I symlink `/etc/kernel -> portage/kernel`, and keep /etc/portage in git.
When cloning my git repository, or otherwise cleaning it, all non-user-created configs go along with it (I'd rather not keep them in git as well, as they might differ across package versions). This isn't a problem for optional things like /etc/portage/savedconfig, but this package requires the files to be present to exhibit the proper functionality.

Though, I don't want to make this purely about my config. One thing that I've noticed happening in the linux ecosystem a lot as of recent, is system-provided configuration files being moved into /usr, and I believe installkernel could do this as well, to be more in line with modern expectations.

This is a feature request to move default-installed files from /etc/kernel/{pre,post}inst.d into /usr/lib or /usr/share/installkernel/{pre,post}inst.d. Any identically-named files in the /etc equivalent would override the system-provided equivalents.

**Comment by AndrewAmmerlaan** [comment]
This is already the case when systemd's kernel-install is used (i.e. ˋUSE=systemdˋ). 

The problem you are describing (not holding to the /etc vs /usr/lib convention when it comes to default config files installed by the package manager) is one of the reasons systemd's kernel-install is better than the traditional installkernel. And it is one of the reasons it is enabled by default (on systemd profiles that have systemd installed anyway).

I don't really want to change the legacy installkernel to be more like systemd's kernel-install because that is basically reinventing a tool that works well (but without what some would consider the "taint" of the systemd name). I personally would consider this a waste of time, since users of openrc can still use systemd's kernel-install via ˋsys-apps/systemd-utils[kernel-install]ˋ and get all the benefits that come with this. That being said, if someone else wants to work on improving the legacy installkernel, then I'll of course be happy to review any pull requests.

**Comment by mid-kid** [comment]
That makes sense, but it also makes me wonder if it would be simpler to just implement support for the systemd-style hooks, instead of having all this duplicate hook code.

Still, though, I care a fair bit about defaults, and the default currently installs both flavors of hook scripts regardless of the USE flag, making it a bit of an awkward situation.

I might look into it at some point, if nobody else gets to it. Thanks for the comment!

**Comment by AndrewAmmerlaan** [comment]
> Still, though, I care a fair bit about defaults, and the default currently installs both flavors of hook scripts regardless of the USE flag, making it a bit of an awkward situation.

This is because whether or not `kernel-install` is called can be toggled at runtime, the USE flag just switches the default. The design I am aiming for is to have as much as possible runtime configurable because users sometimes want different installation mechanisms for different kernels on the same machine.

> That makes sense, but it also makes me wonder if it would be simpler to just implement support for the systemd-style hooks, instead of having all this duplicate hook code.

Those plugins expect certain settings to be set from `install.conf`, so going this route would also mean reading from that config file. And before you know it, you then have made a functionally identical copy of systemd's `kernel-install`, which you then have to keep somewhat synced to the systemd version to avoid breaking one or more of the plugin scripts. That is a maintenance load I'd rather avoid, and for that reason I'd prefer to keep these things separate. 

The easiest solution (also in terms of maintainability) that would also reduce confusion among users, is to just have only one method of kernel installation, i.e. make the new systemd hooks fully the same as the traditional installkernel and then drop the legacy code path. But this gives everyone who wants to use `installkernel` a dependency on `sys-apps/systemd(-utils)` which is a course I dare not peruse as it will just make a lot of people angry and potentially break some setups (again).

**Comment by mid-kid** [comment]
> Those plugins expect certain settings to be set from install.conf, so going this route would also mean reading from that config file. And before you know it, you then have made a functionally identical copy of systemd's kernel-install, which you then have to keep somewhat synced to the systemd version to avoid breaking one or more of the plugin scripts. That is a maintenance load I'd rather avoid, and for that reason I'd prefer to keep these things separate.

Maybe instead of explicitly supporting systemd-style hooks in installkernel, the hooks could be written in such a way as to call eachother and support both environments without duplicate code. Wouldn't directly solve my OP question but it may ease maintainability.

Anyway, yeah, I understand. It's a bit of a silly situation, but installkernel is incredibly simple thankfully.

**Comment by AndrewAmmerlaan** [comment]
So I said earlier that changing the traditional installkernel to be more like systemd's kernel-install wasn't something I wanted to do. But I got a bit bored today and did it anyway. Now plugins provided by the package are installed into `/usr/lib` and as with the systemd version, plugins in `/etc/` override plugins in `/usr/lib/`.

**Comment by mid-kid** [comment]
haha you got bored way quicker than I did
Thanks a lot!
