### ISSUE TITLE
efistub USE flag still requires systemd USE flag

### ISSUE THREAD

**Issue by Biosias** [projg2/installkernel-gentoo#21]
I want to test the newly added efistub on my machines. However efistub USE flag requires systemd USE flag so I'm unable to do it.

**Comment by AndrewAmmerlaan** [comment]
> I want to test the newly added efistub on my machines. However efistub USE flag requires systemd USE flag so I'm unable to do it.

Yes this requires systemd's ˋkernel-installˋ because:
- we need to know the location of the ESP which kernel-install can tell us
- we need to be able to remove entries again which is not possible with debian's installkernel

However, systemd's ˋkernel-installˋ does not require systemd itself, it is also provided by ˋsys-apps/systemd-utilsˋ. So simply enabling the ˋbootˋ and ˋkernel-installˋ flags in systemd-utils will do the trick.

**Comment by AndrewAmmerlaan** [comment]
Updated the wiki pages for Unified Kernel Images, Installkernel, and EFI Stub. Instructions on setting this up are here: https://wiki.gentoo.org/wiki/EFI_stub#Automated 

Please let me know if this is unclear or does not work.

I'll close this issue since there is nothing to do here, we need the more advanced `kernel-install` from systemd instead of the traditional `installkernel` from Debian, but this requirement does not create a dependency on the systemd init system as the `kernel-install` tool functions just fine without it and is provided stand-alone via `sys-apps/systemd-utils`.
