### ISSUE TITLE
Installing kernel images to multiple EFI partitions at the same time

### ISSUE THREAD

**Issue by Biosias** [projg2/installkernel-gentoo#29]
Hello,

I have a question if it would be possible to add for example a use flag which would enable installkernel to install kernel image into all mounted EFI partitions at the same time.

Posting this just to start a discussion.

**Comment by AndrewAmmerlaan** [comment]
Not sure how this could be done to be honest, the current (non-systemd) code does not care about mount points at all. It simply looks for our vendor directory in common locations (`eclean-kernel` does the same). This simplicity makes it robust in my opinion (we already know that detecting the ESP(s) by PARTTYPE in a chroot sometimes does not work).

The script does have the option to install to a custom directory, by specifying a fourth argument:
```
echo "Usage: installkernel <version> <image> <System.map> <directory>"
```
It should be possible to write some custom wrapper that does the equivalent of `for efi_dir in my_efi_dirs; do installkernel ... efi_dir; done`. However, the current code does not execute any post_install or pre_install plugins if the fourth argument is set to something other then the default location (`/boot`). I'm not sure why this is the case, it was already like that when I started working on this. Because I don't understand the reason for this, I am hesitant to change it.

The systemd implementation is another story, you can simply give it the `--esp-path=PATH` argument and loop over all your ESPs. In theory that should work, but I have never tried this.

**Comment by Biosias** [comment]
Ok I understand.

In this case would a post install plugin which would just always copy the image into every mounted efi partition if some useflag is enabled make sense?

To completely avoid passing any arguments to installkernel.

**Comment by AndrewAmmerlaan** [comment]
> In this case would a post install plugin which would just always copy the image into every mounted efi partition if some useflag is enabled make sense?

That would work, the installed image is passed as an argument to the postinst plugins.

**Comment by Biosias** [comment]
Good, I'll experiment with it and will open PR when I'll have something that works
